<?php

declare(strict_types=1);

namespace Some\NamespacePath\Blog\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Some\NamespacePath\Blog\Http\Requests\Concerns\ProvidesPostRules;
use Some\NamespacePath\Blog\Models\Post;

class StorePostRequest extends FormRequest
{
    use ProvidesPostRules;

    public function authorize(): bool
    {
        return $this->user()?->can('create', Post::class) ?? false;
    }

    /**
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return $this->postRules(creating: true);
    }

    protected function prepareForValidation(): void
    {
        // Normalise input; the slug stays optional and is uniquely generated by
        // the HasSlug trait when omitted (so we never pre-empt it with a 422).
        if (is_string($this->title)) {
            $this->merge(['title' => trim($this->title)]);
        }
    }
}
